export function getPlaylistsByUser(userId) {
    return ["Playlist 1", 
        "Playlist 2", 
        "Playlist 3",
        "Playlist 2", 
        "Playlist 2", 
        "Playlist 2", 
        "Playlist 2", 
        "Playlist 2", 
        "Playlist 2", 
        "Playlist 2", 
        "Playlist 3",
        "Playlist 2", 
        "Playlist 3",
        "Playlist 2", 
        "Playlist 3",
        "Playlist 2", 
        "Playlist 3",
        "Playlist 2", 
        "Playlist 3",
        "Playlist 2", 
        "Playlist 3",
    ];
}
